### ISSUE TITLE
error

### ISSUE THREAD

**Issue by felix63** [jseidl/hass-magic_areas#135]
When running magic areas I have the following error twice on startup:

`2021-08-25 00:41:35 ERROR (MainThread) [homeassistant.components.light] Error while setting up magic_areas platform for light
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 587, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 710, in add_to_platform_finish
await self.async_added_to_hass()
File "/usr/src/homeassistant/homeassistant/components/group/light.py", line 113, in async_added_to_hass
async_track_state_change_event(
File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 249, in async_track_state_change_event
entity_ids = _async_string_to_lower_list(entity_ids)
File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 526, in _async_string_to_lower_list
return [mstr.lower() for mstr in instr]
File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 526, in <listcomp>
return [mstr.lower() for mstr in instr]
AttributeError: 'list' object has no attribute 'lower'`

Version | core-2021.8.6
-- | --
Installation Type | Home Assistant Container
Development | false
Supervisor | false
Docker | true
user | root
Virtual Environment | false
Python Version | 3.9.6
Operating System Family | Linux
Operating System Version | 5.8.0-63-generic
CPU Architecture | x86_64
Timezone | Europe/Amsterdam

Installed Version | 1.14.1
Stage | running

<br class="Apple-interchange-newline" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">

**Comment by jseidl** [comment]
Thanks for reporting. Unfortunately the stack trace ends before I can see where the issue is in the Magic Areas code. Will investigate.

**Comment by felix63** [comment]
btw the error has disappeared. So we can close this one :-)
