### ISSUE TITLE
Error while configuring the area

### ISSUE THREAD

**Issue by DeerMaximum** [jseidl/hass-magic_areas#172]
I have freshly installed the integration and wanted to edit an area. Thereby the error message appears: The configuration flow could not be loaded.

There is one bad log entry:
```Logger: aiohttp.server
Source: custom_components/magic_areas/config_flow.py:130
Integration: Magic Areas (documentation, issues)
First occurred: 20:45:52 (1 occurrences)
Last logged: 20:45:52

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 220, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 181, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 192, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 203, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 230, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 325, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/magic_areas/config_flow.py", line 130, in async_step_init
    CONF_MAIN_LIGHTS: cv.multi_select(sorted(all_lights)),
TypeError: '<' not supported between instances of 'list' and 'str'
```

**Comment by jseidl** [comment]
Thanks for your PR! I'll be merging shortly. Can you elaborate on the root cause of the issue?

**Comment by DeerMaximum** [comment]
I had a group of lights in one area. These are returned by ha as list.
With the group, `all_lights` looked like this: `["light.one", "light.two", ["light.three", "light.four"]]`
That has thrown the error. The PR resolves the inner list and inserts the entities into the outer one.
