### ISSUE TITLE
ERROR [homeassistant.setup] Unable to prepare setup for platform 'magic_areas.climate': Platform not found (Exception importing custom_components.magic_areas.climate).

### ISSUE THREAD

**Issue by juacas** [jseidl/hass-magic_areas#304]
**Describe the bug**
Every reboot there are a pair of notifications of magic_areas (supossedly) failing to initialize.
The log shows some errors like this:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/magic_areas/climate.py", line 44, in <module>
    SUPPORT_TARGET_TEMPERATURE | SUPPORT_TARGET_TEMPERATURE_RANGE | SUPPORT_PRESET_MODE
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'SUPPORT_TARGET_TEMPERATURE' is not defined
```
Also, there are deprecated symbols warnings about TEMP_CELSIUS and TEMP_FAHRENHEIT.

Aparently, Magic Areas works fine despite this.
I don't use any climate group, anyways.

**To Reproduce**
1. Restart HA
2. Look at "notifications"
3. Look at logs.

**Expected behavior**
No errors and no warnings.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: HA 2024.1.0
 - Browser: Not depend on browser.
 - Version: Magic Areas 3.0.2

**Smartphone (please complete the following information):**

**Additional context**
This is a great component. Thank you.

**Comment by juacas** [comment]
Hi @jseidl, 
it seems that this issue will be fully fixed in next release.
In that case, accept my apologizes and I'll be looking forward the new refactored release.
Regards.

**Comment by jseidl** [comment]
Hi! Yes that was fixed already and it's coming up soon after I test it.
