### ISSUE TITLE
Bug: Unable to configure. Log shows failure on startup

### ISSUE THREAD

**Issue by mingofmongo2** [jseidl/hass-magic_areas#319]
**Describe the bug**
I get the following error message on bootup:

2024-02-19 22:14:54.510 DEBUG (MainThread) [custom_components.magic_areas] Area names are valid (not using reserved names), continuing...
2024-02-19 22:14:54.510 DEBUG (MainThread) [custom_components.magic_areas] Appending Meta Area Global to the list of areas
2024-02-19 22:14:54.510 ERROR (MainThread) [homeassistant.setup] Error during setup of component magic_areas
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 333, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/magic_areas/__init__.py", line 67, in async_setup
    AreaEntry(
TypeError: AreaEntry.__init__() missing 2 required keyword-only arguments: 'icon' and 'picture'

**To Reproduce**
1. Install Magic Areas
2. Add to configuration.yaml
3. Restart

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Smartphone (please complete the following information):**
 - Device: HA Yellow

**Additional context**
Thanks for your help!

**Comment by mingofmongo2** [comment]
[home-assistant.log](https://github.com/jseidl/hass-magic_areas/files/14330439/home-assistant.log)

**Comment by mingofmongo2** [comment]
I removed any apostrophes from room names, deleted empty rooms, and added icons for each room . Still no success I'm afraid.

**Comment by jseidl** [comment]
Hi, this is likely a duplicate of https://github.com/jseidl/hass-magic_areas/issues/316. Home Assistant 2024.2 changed some required fields in the Area object. There's an update in beta going on but it will only be released this weekend. You can either join the beta or manually fix 1 file, see the link. 

Let me know if you still have questions

**Comment by mingofmongo2** [comment]
Thanks Jan for looking at this so quickly - will wait for the fix. Cheers!
